#include "arduino_secrets.h"
/* 
  Sketch generated by the Arduino IoT Cloud Thing "ultrasonic"
  https://create.arduino.cc/cloud/things/94cc8251-2304-478c-9822-20fee9389cc8 

  Arduino IoT Cloud Properties description

  The following variables are automatically generated and updated when changes are made to the Thing properties

  float washing;

  Properties which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
#include <Servo.h>

Servo servo1;
int trigPin = 2;
int echoPin = 3;
long distance;
long duration;
bool washing = false;
const int buzzer = 4;
int pirPin = 5;                 
int pirStat = 0;
int x = 0;
float washing=0;

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 
    servo1.attach(1);
  pinMode(trigPin, OUTPUT);
  pinMode(echoPin, INPUT);// put your setup code here, to run once:
  servo1.write(0);
  pinMode(buzzer, OUTPUT);
  servo1.write(0);
  Serial.begin(9600);

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
   ping();
  pirStat = digitalRead(pirPin);

  delay(500);
  if (distance <= 5) {
    delay(3000);
    servo1.write(90);
    delay(2000);
    washing = true;

    if (distance >= 5) {
      for (x = 1; x <= 20;) {
        tone(buzzer, 1000);
        delay(1000);
        x++;
        Serial.println(x);
        if (pirStat == HIGH) {
          washing = x;
          break;
        }
      }

    }


  }
  else {
    servo1.write(0);
    noTone(buzzer);
  }

  
  
}
void ping() {
  digitalWrite(trigPin, LOW);
  delayMicroseconds(2);
  digitalWrite(trigPin, HIGH);
  delayMicroseconds(10);
  digitalWrite(trigPin, LOW);
  duration = pulseIn(echoPin, HIGH);
  distance = duration * 0.034 / 2;
}


void onWashingChange() {
  Serial.println("Updated");
}

